name: Build and Test Dashboard Widget

on:
  push:
    branches:
      - master
  pull_request:

env:
  TELESERO_NPM_TOKEN: ${{ secrets.TELESERO_NPM_TOKEN }}

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure NPM for Telesero registry
        run: |
          echo "//repo.npm.systems.cxcl.io/:_authToken=${TELESERO_NPM_TOKEN}" > .npmrc
          cp .yarnrc.example .yarnrc

      - name: Install and Test
        run: |
          yarn install --check-files
          yarn lint || true
          yarn test || echo "Tests skipped or no tests configured"
        env:
          CI: true

  build:
    runs-on: ubuntu-latest
    needs: test
    if: "'refs/heads/master' == github.ref"

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure NPM for Telesero registry
        run: |
          echo "//repo.npm.systems.cxcl.io/:_authToken=${TELESERO_NPM_TOKEN}" > .npmrc
          cp .yarnrc.example .yarnrc

      - name: Show current version
        run: cat ./package.json | grep version

      - name: Build package
        run: |
          yarn install --check-files
          yarn build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/
          retention-days: 30
